source 'https://github.com/CocoaPods/Specs.git'

# ignoring warning from pods
inhibit_all_warnings!

use_frameworks!

target "PhotoBrowserDemo" do

pod 'SDWebImage'
pod 'DACircularProgress'
pod 'pop'
pod 'AMImageSequenceView', :git => 'https://github.com/Babonov/AMImageSequenceView', :commit => '844703c14c1e4cd3a2da06a4b75ecfa23b539ff4'

end
